export { default as bakery1 } from './bakery1.png'
export { default as badge } from './badge.png'
export { default as logo } from './logo.png'
export { default as pizza } from './pizza.jpg'
export { default as bread } from './bread.jpg'
export { default as deliveryIcon } from './delivery.svg'
export { default as qrCode } from './QRcode.svg'
export { default as moneyIcon} from './shop.svg'