export { default as bakery1 } from './bakery1.png'
export { default as badge } from './badge.png'
export { default as logo } from './logo.png'
export { default as vegan } from './vegan_thaicury.png'
export { default as bg_vegan} from './background_vegan.png'
export { default as image_discount} from './discount_image.png'